# Generated by Django 3.2.12 on 2022-02-15 23:54

from core.fixtures.urls import WEBSITES
from core.models import Website
from django.db import migrations


def populate_websites(*args, **kwargs):
    if Website.objects.exists():
        return
    objs = Website.objects.bulk_create(WEBSITES)
    print(f">>> {objs.count()} websites were created")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [migrations.RunPython(populate_websites)]
